// <auto-generated />
using CarHistoryService.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace CarHistoryService.Migrations
{
    [DbContext(typeof(StateHistoryDbContext))]
    [Migration("20171226082825_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarHistoryService.Models.AccuHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Charge");

                    b.Property<double>("Current");

                    b.Property<int>("IdAccu");

                    b.Property<int>("IdTimeCode");

                    b.Property<string>("NameAccu");

                    b.Property<double>("Voltage");

                    b.HasKey("Id");

                    b.ToTable("AccuStates");
                });

            modelBuilder.Entity("CarHistoryService.Models.TimeCodeHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IdCar");

                    b.Property<int>("Time");

                    b.HasKey("Id");

                    b.ToTable("TimeCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
